routes/web.php
<?php

use App\Http\Controllers\AnswersController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\FavouritesController;
use App\Http\Controllers\VotesController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/questions', QuestionsController::class)->except('show');
Route::get('/questions/{slug}', [QuestionsController::class, 'show'])->name('questions.show');
Route::resource('questions.answer', AnswersController::class)->except(['create', 'show']);
Route::put('/questions/{question}/answers/{answer}/mark-as-best', [AnswersController::class, 'markAsBest'])->name('questions.answer.markAsBest');
Route::post('/questions/{question}/mark-as-fav', [FavouritesController::class, 'store'])->name('questions.mark-as-fav');

Route::delete('/questions/{question}/mark-as-unfav', [FavouritesController::class, 'destroy'])->name('questions.mark-as-unfav');

Route::post('/questions/{question}/vote/{vote}', [VotesController::class, 'voteQuestion'])->name('questions.vote');

Route::post('/questions/{question}/answers/{answer}/vote/{vote}', [VotesController::class, 'voteAnswer'])->name('answers.vote');

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    use HasFactory;

    protected $guarded = [];

    public static function boot()
    {
        parent::boot();
        static::created(function (Answer $answer) {
            $answer->question->increment('answers_count');
        });

        static::deleted(function (Answer $answer) {
            $answer->question->decrement('answers_count');
        });
    }

    public function question()
    {
        return $this->belongsTo(Question::class);
    }

    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }

    public function getBestAnswerStyleAttribute(Question $question)
    {
        return $this->id === $question->best_answer_id ? 'text-success' : 'text-dark';
    }

    public function votes(){
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }

    public function vote(int $vote){
        $this->votes()->attach(auth()->id(), ['vote' => $vote]);
        if($vote <0){
            $this->decrement('votes_count');
        } else {
            $this->increment('votes_count');
        }
    }

    public function updateVote(int $vote){
        $this->votes()->updateExistingPivot(auth()->id(), ['vote' =>$vote]);
        if($vote <0){
            $this->decrement('votes_count', 2);
        } else {
            $this->increment('votes_count', 2);
        }
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function questions() {
        return $this->hasMany(Question::class);
    }

    public function answer() {
        return $this->hasMany(Answer::class);
    }

    public function getAvatarAttribute()
    {
        $rounded = true;
        $size = 40;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded={$rounded}&size={$size}";
    }

    public function favorites(){
        return $this->belongsToMany(Question::class);
    }

    public function votesQuestion(){
        return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
    }

    public function votesAnswer(){
        return $this->morphedByMany(Answer::class, 'vote')->withTimestamps();
    }

    public function hasQuestionUpVoted(Question $question){
        return $this->votesQuestion()->where(['vote_id' => $question->id, 'vote' =>1])->exists();
    }

    public function hasQuestionDownVoted(Question $question){
        return $this->votesQuestion()->where(['vote_id' => $question->id, 'vote' =>-1])->exists();
    }

    public function hasVoteForQuestion(Question $question){
        return $this->hasQuestionUpVoted($question) || $this->hasQuestionDownVoted($question);
    }

    public function hasAnswerUpVoted(Answer $answer){
        return $this->votesAnswer()->where(['vote_id' => $answer->id, 'vote' =>1])->exists();
    }

    public function hasAnswerDownVoted(Answer $answer){
        return $this->votesAnswer()->where(['vote_id' => $answer->id, 'vote' =>-1])->exists();
    }

    public function hasVoteForAnswer(Answer $answer){
        return $this->hasAnswerUpVoted($answer) || $this->hasAnswerDownVoted($answer);
    }
}

app/Http/Controllers/AnswersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateAnswerRequest;
use App\Http\Requests\MarkAsBestRequest;
use App\Http\Requests\UpdateAnswerRequest;
use App\Models\Answer;
use App\Models\Question;
use Illuminate\Http\Request;

class AnswersController extends Controller
{
    public function store(CreateAnswerRequest $request, Question $question)
    {
        $question->answer()->create([
            'body' => $request->body,
            'user_id' => auth()->id()
        ]);
        session()->flash('success', 'Answer has been added successfully!');
        return redirect($question->url);
    }

    public function edit(Question $question, Answer $answer)
    {
        if($this->authorize('update', $answer))
        {
            return view('answers._edit', compact([
                'question',
                'answer'
            ]));
        }
        abort(403);
    }

    public function update(UpdateAnswerRequest $request, Question $question, Answer $answer)
    {
        $answer->update([
            'body' => $request->body
        ]);

        session()->flash('success', 'Answer has been updated successfully!');
        return redirect($question->url);
    }

    public function destroy(Question $question, Answer $answer)
    {
            $this->authorize('delete', [$answer, $question]);
            $answer->delete();

            session()->flash('success', 'Answer has been deleted successfully!');
            return redirect()->back();


    }

    public function markAsBest(MarkAsBestRequest $request, Question $question, Answer $answer)
    {
        $this->authorize('markAsBest', $question);
        if($answer->question->id !== $question->id) {
            abort(403);
        }
        $question->markAsBest($answer);
        return redirect()->back();
    }
}

resources/views/answers/_create.blade.php
@push('styles')
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.0/dist/trix.css">
@endpush
@section('scripts')
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.0/dist/trix.umd.min.js"></script>
@endsection

<div class="row mt-4 justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3>Your Answer!</h3>
            </div>
            <div class="card-body">
                <form action="{{ route('questions.answer.store', $question->id) }}" method="POST">
                    @csrf
                    <div class="form-group mt-3">
                        <label for="body" class="form-label">Body</label>
                        <input type="hidden" name="body" id="body" placeholder="Enter Question" value="{{ old('body') }}" class="form-control @error('body') is-invalid @enderror" />
                        <trix-editor input="body"></trix-editor>
                        @error('body')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="form-group mt-2">
                        <button type="submit" class="btn btn-outline-success">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/answers/_edit.blade.php
@extends('layouts.app')

@push('styles')
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.0/dist/trix.css">
@endpush

@section('scripts')
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.0/dist/trix.umd.min.js"></script>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h1>Edit Your Answer</h1></div>
                    <div class="card-body">
                        <form action="{{ route('questions.answer.update', [$question->id, $answer->id]) }}" method="POST">
                            @csrf
                            @method('PUT')
                            {{-- <div class="form-group">
                                <label for="title" class="form-label">Title</label>
                                <input type="text" name="title" id="title" placeholder="Enter Question Title" value="{{ old('title', $answer->title) }}" class="form-control @error('title') is-invalid @enderror" />
                                @error('title')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div> --}}
                            <div class="form-group mt-3">
                                <label for="body" class="form-label">Body</label>
                                <input type="hidden" name="body" id="body" placeholder="Enter Answer" value="{{ old('body', $answer->body) }}" class="form-control @error('body') is-invalid @enderror" />
                                <trix-editor input="body"></trix-editor>
                                @error('body')
                                <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group mt-3">
                                <input type="submit" name="submit" id="submit" class="btn btn-success"/>
                                @error('title')
                                <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/answers/_index.blade.php
<div class="row mt-4">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3>{{ \Illuminate\Support\Str::plural('Answer', $question->answers_count) }}</h3>
            </div>
            <div class="card-body">
                @foreach($question->answer as $answer)
                    {!! $answer->body !!}

                    <div class="d-flex justify-content-between me-3">
                        <div class="d-flex">
                            <div>
                                <a href="#" title="Up Vote" class="up-vote d-block text-center text-dark"><i class="fa fa-caret-up fa-3x"></i></a>
                                <h4 class="vote-count text-muted text-center m-0">{{ $question->votes_count }}</h4>
                                <a href="#" title="Down Vote" class="down-vote d-block text-center text-dark"><i class="fa fa-caret-down fa-3x"></i></a>
                            </div>
                            <div class="mt-2">
                                @can('markAsBest', $question)
                                    <form action="{{ route('questions.answer.markAsBest', [$question->id, $answer->id]) }}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <button type="submit" class="btn {{ $answer->getBestAnswerStyleAttribute($question) }}">
                                            <i class="fa fa-check fa-2x"></i>
                                        </button>
                                    </form>
                                @else
                                    <button type="button" class="btn {{ $answer->getBestAnswerStyleAttribute($question) }}">
                                        <i class="fa fa-check fa-2x"></i>
                                    </button>
                                @endcan
                            </div>
                            <div class="ms-4 mt-3 d-flex">
                                @can('update', $answer)
                                    <div class="me-2">
                                        <a href="{{ route('questions.answer.edit', [$question->id, $answer->id]) }}" class="btn btn-sm btn-outline-info">Edit</a>
                                    </div>
                                @endcan
                                @can('delete', [$answer, $question])
                                    <form action="{{ route('questions.answer.destroy', [$question->id, $answer->id]) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-outline-danger">Delete</button>
                                    </form>
                                @endcan
                            </div>
                        </div>
                        <div>
                            <div class="text-muted mb-2 text-end">
                                Answered: {{ $answer->created_date }}
                            </div>
                            <div class="d-flex mb-2">
                                <div>
                                    <img src="{{ $answer->author->avatar }}">
                                </div>
                                <div class="mt-2">
                                    {{ $answer->author->name }}
                                </div>
                            </div>
                        </div>
                    </div>

                    <hr>
                @endforeach
            </div>
        </div>
    </div>
</div>