routes/web.php
<?php

use App\Http\Controllers\AnswersController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\FavouritesController;
use App\Http\Controllers\VotesController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/questions', QuestionsController::class)->except('show');
Route::get('/questions/{slug}', [QuestionsController::class, 'show'])->name('questions.show');
Route::resource('questions.answer', AnswersController::class)->except(['create', 'show']);
Route::put('/questions/{question}/answers/{answer}/mark-as-best', [AnswersController::class, 'markAsBest'])->name('questions.answer.markAsBest');
Route::post('/questions/{question}/mark-as-fav', [FavouritesController::class, 'store'])->name('questions.mark-as-fav');

Route::delete('/questions/{question}/mark-as-unfav', [FavouritesController::class, 'destroy'])->name('questions.mark-as-unfav');

Route::post('/questions/{question}/vote/{vote}', [VotesController::class, 'voteQuestion'])->name('questions.vote');

Route::post('/questions/{question}/answers/{answer}/vote/{vote}', [VotesController::class, 'voteAnswer'])->name('answers.vote');

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class Question extends Model
{
    use HasFactory;

    protected $guarded = [];
    // Below are the mutators. Mutators means in which we set the attributes automatically.
    public function setTitleAttribute(string $title) {
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = Str::slug($title);
    }

    public function owner() {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function markAsBest(Answer $answer)
    {
        $this->update(['best_answer_id' => $answer->id]);
    }


    public function getUrlAttribute() {
        return "/questions/$this->slug";
    }

    public function getCreatedDateAttribute() {
        return $this->created_at->diffForHumans();
    }

    public function getAnswerStylesAttribute() {
        if($this->answers_count > 0) {
            if($this->best_answer_id) {
                return 'has-best-answer';
            }
            return 'answered';
        }
        return 'unanswered';
    }

    public function favorites(){
        return $this->belongsToMany(User::class);
    }

    public function getFavoritesCountAttribute(){
        return $this->favorites()->count();
    }

    public function getIsFavoriteAttribute(){
        return $this->favorites()->where('user_id', auth()->id())->count() > 0;
    }

    public function answer(){
        return $this->hasMany(Answer::class);
    }

    public function votes(){
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }

    public function vote(int $vote){
        $this->votes()->attach(auth()->id(), ['vote' => $vote]);
        if($vote <0){
            $this->decrement('votes_count');
        } else {
            $this->increment('votes_count');
        }
    }

    public function updateVote(int $vote){
        $this->votes()->updateExistingPivot(auth()->id(), ['vote' =>$vote]);
        if($vote <0){
            $this->decrement('votes_count', 2);
        } else {
            $this->increment('votes_count', 2);
        }
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function questions() {
        return $this->hasMany(Question::class);
    }

    public function answer() {
        return $this->hasMany(Answer::class);
    }

    public function getAvatarAttribute()
    {
        $rounded = true;
        $size = 40;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded={$rounded}&size={$size}";
    }

    public function favorites(){
        return $this->belongsToMany(Question::class);
    }

    public function votesQuestion(){
        return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
    }

    public function votesAnswer(){
        return $this->morphedByMany(Answer::class, 'vote')->withTimestamps();
    }

    public function hasQuestionUpVoted(Question $question){
        return $this->votesQuestion()->where(['vote_id' => $question->id, 'vote' =>1])->exists();
    }

    public function hasQuestionDownVoted(Question $question){
        return $this->votesQuestion()->where(['vote_id' => $question->id, 'vote' =>-1])->exists();
    }

    public function hasVoteForQuestion(Question $question){
        return $this->hasQuestionUpVoted($question) || $this->hasQuestionDownVoted($question);
    }

    public function hasAnswerUpVoted(Answer $answer){
        return $this->votesAnswer()->where(['vote_id' => $answer->id, 'vote' =>1])->exists();
    }

    public function hasAnswerDownVoted(Answer $answer){
        return $this->votesAnswer()->where(['vote_id' => $answer->id, 'vote' =>-1])->exists();
    }

    public function hasVoteForAnswer(Answer $answer){
        return $this->hasAnswerUpVoted($answer) || $this->hasAnswerDownVoted($answer);
    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;
use App\Http\Requests\CreateQuestionRequest;
use App\Http\Requests\UpdateQuestionRequest;
use App\Models\Question;
use Illuminate\Http\Request;

class QuestionsController extends Controller
{
    public function __construct() {
        $this->middleware(['auth'])->only(['create', 'store']);
    }

    public function index()
    {
        $questions = Question::with('owner')->latest()->paginate(10);
        return view('questions.index', compact(['questions']));
    }

    public function create()
    {
        return view('questions.create');
    }

    public function store(CreateQuestionRequest $request)
    {
        auth()->user()->questions()->create([
            'title'=>$request->title,
            'body'=>$request->body
        ]);

        session()->flash('success', 'Question has been added successfully!');
        return redirect(route('questions.index'));
    }

    public function edit(Question $question)
    {
        if($this->authorize('update', $question)) {
            return view('questions.edit', compact([
                'question'
            ]));
        }
        abort(403);
    }

    public function update(UpdateQuestionRequest $request, Question $question)
    {
        if($this->authorize('update', $question)) {
            $question->update([
                'title'=>$request->title,
                'body'=>$request->body
            ]);

            session()->flash('success', 'Question has been updated successfully!');
            return redirect(route('questions.index'));
        }
        abort(403);
    }

    public function show(Question $question)
    {
        $question->increment('views_count');
        return view('questions.show', compact([
            'question'
        ]));
    }

    public function destroy(Question $question)
    {
        if($this->authorize('delete', $question)) {
            $question->delete();

            session()->flash('success', 'Question has been deleted successfully!');
            return redirect(route('questions.index'));

        }
        abort(403);
    }
}

resources/views/questions/create.blade.php
@extends('layouts.app')

@push('styles')
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.0/dist/trix.css">
@endpush

@section('scripts')
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.0/dist/trix.umd.min.js"></script>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h1>Ask a Question!</h1></div>
                    <div class="card-body">
                        <form action="{{ route('questions.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="title" class="form-label">Title</label>
                                <input type="text" name="title" id="title" placeholder="Enter Question Title" value="{{ old('title') }}" class="form-control @error('title') is-invalid @enderror" />
                                @error('title')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group mt-3">
                                <label for="body" class="form-label">Body</label>
                                <input type="hidden" name="body" id="body" placeholder="Enter Question" value="{{ old('body') }}" class="form-control @error('body') is-invalid @enderror" />
                                <trix-editor input="body"></trix-editor>
                                @error('body')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group mt-3">
                                <input type="submit" name="submit" id="submit" class="btn btn-success"/>
                                @error('title')
                                <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.0/dist/trix.css">
@endsection

@section('scripts')
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.0/dist/trix.umd.min.js"></script>
@endsection
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h1>Ask a Question!</h1></div>
                    <div class="card-body">
                        <form action="{{ route('questions.update', $question->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="title" class="form-label">Title</label>
                                <input type="text" name="title" id="title" placeholder="Enter Question Title" value="{{ old('title', $question->title) }}" class="form-control @error('title') is-invalid @enderror" />
                                @error('title')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group mt-3">
                                <label for="body" class="form-label">Body</label>
                                <input type="hidden" name="body" id="body" placeholder="Enter Question" value="{{ old('body', $question->body) }}" class="form-control @error('body') is-invalid @enderror" />
                                <trix-editor input="body"></trix-editor>
                                @error('body')
                                <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group mt-3">
                                <input type="submit" name="submit" id="submit" class="btn btn-success"/>
                                @error('title')
                                <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <div><h1>All Questions</h1></div>
                        <div class="align-self-center mb-2">
                            <a href="{{ route('questions.create')}}" class="btn btn-warning">Ask a Question</a>
                        </div>
                    </div>
                    @foreach($questions as $question)
                        <div class="card-body">
                            <div class="d-flex align-items-center">
                                <div class="flex-shrink-0 statistics">
                                    <div class="votes text-center mb-3">
                                        <strong class="d-block">{{ $question->votes_count }}</strong> Votes
                                    </div>
                                    <div class="votes text-center mb-3 answers {{ $question->answer_styles }}">
                                        <strong class="d-block">{{ $question->answers_count }}</strong> Answers
                                    </div>
                                    <div class="votes text-center mb-3">
                                        <strong class="d-block">{{ $question->views_count }}</strong> Views
                                    </div>
                                </div>
                                <div class="flex-grow-1 ms-3">
                                    <div class="d-flex justify-content-between">
                                        <h4>
                                            <a href="{{ $question->url }}">{{ $question->title }}</a>
                                        </h4>

                                        <div class="d-flex">
                                            @can('update', $question)
                                                <a href="{{ route('questions.edit', $question->id) }}" class="btn btn-outline-info me-2">Edit</a>
                                            @endcan
                                            @can('delete', $question)
                                                <form action="{{ route('questions.destroy', $question->id) }}" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                                                </form>
                                            @endcan
                                        </div>
                                    </div>
                                    <p>
                                        Asked By: <a href="#">{{ $question->owner->name }}</a>
                                        <span class="text-muted">{{ $question->created_date }}</span>
                                    </p>
                                    <p>
                                        {!! \Illuminate\Support\Str::limit($question->body, 250) !!}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <hr>
                    @endforeach

                    <div class="card-footer">
                        {{ $questions->links('vendor.pagination.bootstrap-5') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@push('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
@endpush
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h1>{{ $question->title }}</h1>
                    </div>
                    <div class="card-body">
                        {!! $question->body !!}
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-between me-3">
                            <div class="d-flex">
                                <div>
                                    @auth
                                        <form action="{{ route('questions.vote', [$question->id, 1]) }}" method="POST">
                                            @csrf
                                            <button type="submit" title="Up Vote" class="up-vote d-block text-center {{ auth()->user()->hasQuestionUpVoted($question) ? 'text-success' : 'text-dark' }} btn"><i class="fa fa-caret-up fa-3x"></i></button>
                                        </form>
                                    @else
                                        <h5>Votes <br> Count</h5>
                                    @endauth
{{--                                    <a href="#" title="Up Vote" class="up-vote d-block text-center text-dark"><i class="fa fa-caret-up fa-3x"></i></a>--}}
                                    <h4 class="vote-count text-muted text-center m-0">{{ $question->votes_count }}</h4>
                                    @auth
                                        <form action="{{ route('questions.vote', [$question->id, -1]) }}" method="POST">
                                            @csrf
                                            <button type="submit" title="Down Vote" class="up-vote d-block text-center {{ auth()->user()->hasQuestionDownVoted($question) ? 'text-success' : 'text-dark' }} btn"><i class="fa fa-caret-down fa-3x"></i></button>
                                        </form>
                                    @endauth
{{--                                    <a href="#" title="Down Vote" class="down-vote d-block text-center text-dark"><i class="fa fa-caret-down fa-3x"></i></a>--}}
                                </div>
                                <div class="ms-4 mt-3 {{ $question->is_favorite ? 'text-warning' : 'text-dark' }}">
                                    @can('markAsFav', $question)
                                        <form action="{{ $question->is_favorite ?  route('questions.mark-as-unfav', $question->id) : route('questions.mark-as-fav', $question->id)}}" method="POST">
                                            @csrf
                                            @if($question->is_favorite)
                                                @method('DELETE')
                                            @endif
                                            <button type="submit" class="favorite btn d-block text-center mb-1 {{ $question->is_favorite ? 'text-warning' : 'text-dark' }}"><i class="fa fa-star fa-2x"></i></button>
                                        </form>
                                    @else
                                        <div><i class="fa fa-star fa-2x"></i></div>
                                    @endcan
                                    <h4 class="fav-count m-0 text-center">{{ $question->favorites_count }}</h4>
                                </div>
                            </div>
                            <div>
                                <div class="text-muted mb-2 text-end">
                                    Asked: {{ $question->created_date }}
                                </div>
                                <div class="d-flex mb-2">
                                    <div>
                                        <img src="{{ $question->owner->avatar }}">
                                    </div>
                                    <div class="mt-2">
                                        {{ $question->owner->name }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @auth()
            @include('answers._create')
        @endauth
        @include('answers._index')
    </div>
@endsection